### ISSUE TITLE
Contacting GlobalMEMS

### ISSUE THREAD

**Issue by rblakesley** [GlobalMEMS/Datasheets#1]
Hello,

It looks like the GlobalMEMS website is down, and the sales@globalmems.com email address does not work at the moment.  Is there an alternative way of contacting your company?

Many thanks!

**Comment by JosephAtGMEMS** [comment]
You may contact joseph@globalmems.com if you have any questions about the
datasheets. Thanks.

Richard Blakesley <notifications@github.com> 於 2020年11月6日 週五 下午7:46寫道：
